---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Lion.
--- DateTime: 2019/4/12 16:34
---

FSMState = {}
FSMState.__Index = FSMState

function FSMState:Create()
    local copy = {}
    setmetatable(copy, self)
    return copy
end

function FSMState:OnEnter()

end

function FSMState:CopyState()

end

function FSMState:Update()

end

function FSMState:OnLeave()

end